providers = ["node"]

[phases.setup]
cmds = ["curl -sSL https://get.wasp-lang.dev/installer.sh | sh"]

[phases.build]
cmds = [
  "export PATH=$PATH:$HOME/.local/bin",
  "wasp build"
]

[start]
cmd = "cd .wasp/build && npm start"
