providers = ["node"]

[phases.setup]
cmds = ["npm install -g @wasp-lang/wasp@latest"]

[phases.install]
cmds = ["npm install --production=false"]

[phases.build]
cmds = [
  "wasp db migrate-deploy",
  "wasp build"
]

[start]
cmd = "cd .wasp/build && npm start"
