providers = ["node"]

[variables]
NODE_VERSION = "18"

[phases.setup]
cmds = ["npm --version", "node --version"]

[phases.install]
cmds = ["npm ci --only=production"]

[phases.build]
cmds = [
  "npx wasp db migrate-deploy",
  "npx wasp build"
]

[start]
cmd = "cd .wasp/build && npm start"
